DROP TABLE IF EXISTS players CASCADE;

CREATE TABLE players (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  wins INTEGER NOT NULL
);